/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.dkpro.statistics.agreement.coding;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.offset;

import java.io.IOException;
import java.util.stream.Stream;

import org.dkpro.statistics.agreement.JsonFixtures;
import org.dkpro.statistics.agreement.distance.IntervalDistanceFunction;
import org.dkpro.statistics.agreement.distance.NominalDistanceFunction;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

import tools.jackson.databind.JsonNode;

/**
 * Cross-validation of {@link GwetAC1Agreement} and {@link GwetAC2Agreement} against fixtures
 * generated by Gwet's own reference implementation, the R package
 * <a href="https://CRAN.R-project.org/package=irrCAC">irrCAC</a> (see
 * {@code src/test/scripts/generate_gwet_fixtures.R}). Each fixture holds a two-rater contingency
 * table and, for both an unweighted (AC1) and a quadratic-weighted (AC2) analysis, the observed
 * agreement {@code pa}, the chance agreement {@code pe}, and the resulting coefficient as reported
 * by irrCAC.<br>
 * <br>
 * The mapping to the dkpro measures is:
 * <ul>
 * <li>irrCAC <i>unweighted</i> AC1 &rarr; {@link GwetAC1Agreement} (and {@link GwetAC2Agreement}
 * with a {@link NominalDistanceFunction}).</li>
 * <li>irrCAC <i>quadratic</i> AC2 &rarr; {@link GwetAC2Agreement} with an
 * {@link IntervalDistanceFunction}, since irrCAC's quadratic weights
 * {@code w_kl = 1 - (k-l)^2/(q-1)^2} equal {@code 1 - d(k,l)/d_max} for the squared-difference
 * distance over consecutive integer categories.</li>
 * </ul>
 */
public class GwetFixtureTest
{
    private static final String FIXTURE_DIR = "src/test/resources/gwet";

    /** pa/pe are emitted at full double precision by irrCAC. */
    private static final double PROPORTION_TOL = 1e-9;

    /** irrCAC rounds the published coefficient (coeff.val) to five decimals. */
    private static final double COEFFICIENT_TOL = 1e-5;

    static Stream<String> fixtures() throws IOException
    {
        return JsonFixtures.fixtures(FIXTURE_DIR);
    }

    private static JsonNode load(String aFixture)
    {
        return JsonFixtures.load(FIXTURE_DIR, aFixture);
    }

    /**
     * Rebuilds the two-rater study from a fixture's contingency table using integer categories
     * {@code 1..q} (row = rater 1, column = rater 2).
     */
    private static ICodingAnnotationStudy buildStudy(JsonNode aRoot)
    {
        JsonNode table = aRoot.get("table");
        CodingAnnotationStudy study = new CodingAnnotationStudy(2);
        for (int i = 0; i < table.size(); i++) {
            JsonNode row = table.get(i);
            for (int j = 0; j < row.size(); j++) {
                int count = row.get(j).asInt();
                if (count > 0) {
                    study.addMultipleItems(count, i + 1, j + 1);
                }
            }
        }
        return study;
    }

    private static JsonNode caseFor(JsonNode aRoot, String aMeasure)
    {
        for (JsonNode c : aRoot.get("cases")) {
            if (aMeasure.equals(c.get("measure").asString())) {
                return c;
            }
        }
        throw new IllegalArgumentException("No case for measure " + aMeasure);
    }

    @ParameterizedTest(name = "{0}")
    @MethodSource("fixtures")
    void ac1MatchesIrrCac(String aFixture)
    {
        JsonNode root = load(aFixture);
        JsonNode expected = caseFor(root, "AC1");
        ICodingAnnotationStudy study = buildStudy(root);

        GwetAC1Agreement ac1 = new GwetAC1Agreement(study);
        assertThat(ac1.calculateObservedAgreement()).isCloseTo(expected.get("pa").asDouble(),
                offset(PROPORTION_TOL));
        assertThat(ac1.calculateExpectedAgreement()).isCloseTo(expected.get("pe").asDouble(),
                offset(PROPORTION_TOL));
        assertThat(ac1.calculateAgreement()).isCloseTo(expected.get("coefficient").asDouble(),
                offset(COEFFICIENT_TOL));

        // AC2 with a nominal distance function must reproduce the unweighted AC1.
        GwetAC2Agreement ac2Nominal = new GwetAC2Agreement(study, new NominalDistanceFunction());
        assertThat(ac2Nominal.calculateAgreement())
                .isCloseTo(expected.get("coefficient").asDouble(), offset(COEFFICIENT_TOL));
    }

    @ParameterizedTest(name = "{0}")
    @MethodSource("fixtures")
    void ac2QuadraticMatchesIrrCac(String aFixture)
    {
        JsonNode root = load(aFixture);
        JsonNode expected = caseFor(root, "AC2");
        ICodingAnnotationStudy study = buildStudy(root);

        GwetAC2Agreement ac2 = new GwetAC2Agreement(study, new IntervalDistanceFunction());

        // The measure is defined in terms of disagreement; pa = 1 - D_O and pe = 1 - D_E.
        assertThat(1.0 - ac2.calculateObservedDisagreement())
                .isCloseTo(expected.get("pa").asDouble(), offset(PROPORTION_TOL));
        assertThat(1.0 - ac2.calculateExpectedDisagreement())
                .isCloseTo(expected.get("pe").asDouble(), offset(PROPORTION_TOL));
        assertThat(ac2.calculateAgreement()).isCloseTo(expected.get("coefficient").asDouble(),
                offset(COEFFICIENT_TOL));
    }
}
